[server]
enableXsrfProtection = false
enableCORS = false
port=8080
address=0.0.0.0

[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "warning"